export const institutionsArr = [
  // "MOE Kindergarten @ Alexandra",
  // "MOE Kindergarten @ Anchor Green",
  // "MOE Kindergarten @ Ang Mo Kio",
  // "MOE Kindergarten @ Angsana",
  // "MOE Kindergarten @ Bendemeer",
  // "MOE Kindergarten @ Blangah Rise",
  // "MOE Kindergarten @ Casuarina",
  // "MOE Kindergarten @ Cedar",
  // "MOE Kindergarten @ Dazhong",
  // "MOE Kindergarten @ Elias Park",
  // "MOE Kindergarten @ Farrer Park",
  // "MOE Kindergarten @ Fengshan",
  // "MOE Kindergarten @ Fern Green",
  // "MOE Kindergarten @ Fernvale",
  // "MOE Kindergarten @ First Toa Payoh",
  // "MOE Kindergarten @ Frontier",
  // "MOE Kindergarten @ Gongshang",
  // "MOE Kindergarten @ Greendale",
  // "MOE Kindergarten @ Horizon",
  // "MOE Kindergarten @ Hougang",
  // "MOE Kindergarten @ Huamin",
  // "MOE Kindergarten @ Jing Shan",
  // "MOE Kindergarten @ Junyuan",
  // "MOE Kindergarten @ Jurong West",
  // "MOE Kindergarten @ Kranji",
  // "MOE Kindergarten @ Mayflower",
  // "MOE Kindergarten @ Meridian",
  // "MOE Kindergarten @ Naval Base",
  // "MOE Kindergarten @ North View",
  // "MOE Kindergarten @ North Vista",
  // "MOE Kindergarten @ Northoaks",
  // "MOE Kindergarten @ Northshore",
  // "MOE Kindergarten @ Oasis",
  // "MOE Kindergarten @ Pei Tong",
  // "MOE Kindergarten @ Princess Elizabeth",
  // "MOE Kindergarten @ Punggol",
  // "MOE Kindergarten @ Punggol Cove",
  // "MOE Kindergarten @ Punggol Green",
  // "MOE Kindergarten @ Punggol View",
  // "MOE Kindergarten @ Riverside",
  // "MOE Kindergarten @ Sembawang",
  // "MOE Kindergarten @ Sengkang Green",
  // "MOE Kindergarten @ Shuqun",
  // "MOE Kindergarten @ South View",
  // "MOE Kindergarten @ Springdale",
  // "MOE Kindergarten @ Tampines Primary",
  // "MOE Kindergarten @ Tanjong Katong",
  // "MOE Kindergarten @ Temasek",
  // "MOE Kindergarten @ Valour",
  // "MOE Kindergarten @ Waterway",
  // "MOE Kindergarten @ Wellington",
  // "MOE Kindergarten @ West Spring",
  // "MOE Kindergarten @ West View",
  // "MOE Kindergarten @ Westwood",
  // "MOE Kindergarten @ Yangzheng",
  // "MOE Kindergarten @ Yishun",
  // "MOE Kindergarten @ Zhenghua",
  // "Admiralty Primary School",
  // "Ahmad Ibrahim Primary School",
  // "Ai Tong School",
  // "Alexandra Primary School",
  // "Anchor Green Primary School",
  // "Anderson Primary School",
  // "Ang Mo Kio Primary School",
  // "Anglo-Chinese School (Junior)",
  // "Anglo-Chinese School (Primary)",
  // "Angsana Primary School",
  // "Beacon Primary School",
  // "Bedok Green Primary School",
  // "Bendemeer Primary School",
  // "Blangah Rise Primary School",
  // "Boon Lay Garden Primary School",
  // "Bukit Panjang Primary School",
  // "Bukit Timah Primary School",
  // "Bukit View Primary School",
  // "Canberra Primary School",
  // "Canossa Catholic Primary School",
  // "Cantonment Primary School",
  // "Casuarina Primary School",
  // "Catholic High School (Primary Section)",
  // "Cedar Primary School",
  // "Changkat Primary School",
  // "CHIJ (Katong) Primary",
  // "CHIJ (Kellock)",
  // "CHIJ Our Lady of Good Counsel",
  // "CHIJ Our Lady of the Nativity",
  // "CHIJ Our Lady Queen of Peace",
  // "CHIJ Primary (Toa Payoh)",
  // "CHIJ St. Nicholas Girls' School (Primary Section)",
  // "Chongfu School",
  // "Chongzheng Primary School",
  // "Chua Chu Kang Primary School",
  // "Clementi Primary School",
  // "Compassvale Primary School",
  // "Concord Primary School",
  // "Corporation Primary School",
  // "Damai Primary School",
  // "Dazhong Primary School",
  // "De La Salle School",
  // "East Spring Primary School",
  // "Edgefield Primary School",
  // "Elias Park Primary School",
  // "Endeavour Primary School",
  // "Eunos Primary School",
  // "Evergreen Primary School",
  // "Fairfield Methodist School (Primary)",
  // "Farrer Park Primary School",
  // "Fengshan Primary School",
  // "Fern Green Primary School",
  // "Fernvale Primary School",
  // "First Toa Payoh Primary School",
  // "Frontier Primary School",
  // "Fuchun Primary School",
  // "Fuhua Primary School",
  // "Gan Eng Seng Primary School",
  // "Geylang Methodist School (Primary)",
  // "Gongshang Primary School",
  // "Greendale Primary School",
  // "Greenridge Primary School",
  // "Greenwood Primary School",
  // "Guangyang Primary School",
  // "Haig Girls' School",
  // "Henry Park Primary School",
  // "Holy Innocents' Primary School",
  // "Hong Wen School",
  // "Horizon Primary School",
  // "Hougang Primary School",
  // "Huamin Primary School",
  // "Innova Primary School",
  // "Jiemin Primary School",
  // "Jing Shan Primary School",
  // "Junyuan Primary School",
  // "Jurong Primary School",
  // "Jurong West Primary School",
  // "Keming Primary School",
  // "Kheng Cheng School",
  // "Kong Hwa School",
  // "Kranji Primary School",
  // "Kuo Chuan Presbyterian Primary School",
  // "Lakeside Primary School",
  // "Lianhua Primary School",
  // "Maha Bodhi School",
  // "Maris Stella High School (Primary Section)",
  // "Marsiling Primary School",
  // "Marymount Convent School",
  // "Mayflower Primary School",
  // "Mee Toh School",
  // "Meridian Primary School",
  // "Methodist Girls' School (Primary)",
  // "Montfort Junior School",
  // "Nan Chiau Primary School",
  // "Nan Hua Primary School",
  // "Nanyang Primary School",
  // "Naval Base Primary School",
  // "New Town Primary School",
  // "Ngee Ann Primary School",
  // "North Spring Primary School",
  // "North View Primary School",
  // "North Vista Primary School",
  // "Northland Primary School",
  // "Northoaks Primary School",
  // "Northshore Primary School",
  // "Oasis Primary School",
  // "Opera Estate Primary School",
  // "Palm View Primary School",
  // "Park View Primary School",
  // "Pasir Ris Primary School",
  // "Paya Lebar Methodist Girls' School (Primary)",
  // "Pei Chun Public School",
  // "Pei Hwa Presbyterian Primary School",
  // "Pei Tong Primary School",
  // "Peiying Primary School",
  // "Pioneer Primary School",
  // "Poi Ching School",
  // "Princess Elizabeth Primary School",
  // "Punggol Cove Primary School",
  // "Punggol Green Primary School",
  // "Punggol Primary School",
  // "Punggol View Primary School",
  // "Qifa Primary School",
  // "Qihua Primary School",
  // "Queenstown Primary School",
  // "Radin Mas Primary School",
  // "Raffles Girls' Primary School",
  // "Red Swastika School",
  // "River Valley Primary School",
  // "Riverside Primary School",
  // "Rivervale Primary School",
  // "Rosyth School",
  // "Rulang Primary School",
  // "Sembawang Primary School",
  // "Seng Kang Primary School",
  // "Sengkang Green Primary School",
  // "Shuqun Primary School",
  // "Si Ling Primary School",
  // "Singapore Chinese Girls' Primary School",
  // "South View Primary School",
  // "Springdale Primary School",
  // "St. Andrew's Junior School",
  // "St. Anthony's Canossian Primary School",
  // "St. Anthony's Primary School",
  // "St. Gabriel's Primary School",
  // "St. Hilda's Primary School",
  // "St. Joseph's Institution Junior",
  // "St. Margaret's Primary School",
  // "St. Stephen's School",
  // "Stamford Primary School",
  // "Tampines North Primary School",
  // "Tampines Primary School",
  // "Tanjong Katong Primary School",
  // "Tao Nan School",
  // "Teck Ghee Primary School",
  // "Teck Whye Primary School",
  // "Telok Kurau Primary School",
  // "Temasek Primary School",
  // "Townsville Primary School",
  // "Unity Primary School",
  // "Valour Primary School",
  // "Waterway Primary School",
  // "Wellington Primary School",
  // "West Grove Primary School",
  // "West Spring Primary School",
  // "West View Primary School",
  // "Westwood Primary School",
  // "White Sands Primary School",
  // "Woodgrove Primary School",
  // "Woodlands Primary School",
  // "Woodlands Ring Primary School",
  // "Xinghua Primary School",
  // "Xingnan Primary School",
  // "Xinmin Primary School",
  // "Xishan Primary School",
  // "Yangzheng Primary School",
  // "Yew Tee Primary School",
  // "Yio Chu Kang Primary School",
  // "Yishun Primary School",
  // "Yu Neng Primary School",
  // "Yuhua Primary School",
  // "Yumin Primary School",
  // "Zhangde Primary School",
  // "Zhenghua Primary School",
  // "Zhonghua Primary School",
  "Nil",
  "MR25",
  "Admiralty Secondary School",
  "Ahmad Ibrahim Secondary School",
  "Anderson Secondary School",
  "Ang Mo Kio Secondary School",
  "Anglican High School",
  "Anglo-Chinese School (Barker Road)",
  "Anglo-Chinese School (Independent) (Secondary)",
  "Assumption English School",
  "Assumption Pathway School",
  "Bartley Secondary School",
  "Beatty Secondary School",
  "Bedok Green Secondary School",
  "Bedok South Secondary School",
  "Bedok View Secondary School",
  "Bendemeer Secondary School",
  "Boon Lay Secondary School",
  "Bowen Secondary School",
  "Broadrick Secondary School",
  "Bukit Batok Secondary School",
  "Bukit Merah Secondary School",
  "Bukit Panjang Govt. High School",
  "Bukit View Secondary School",
  "Canberra Secondary School",
  "Catholic High School (Secondary)",
  "Cedar Girls' Secondary School",
  "Changkat Changi Secondary School",
  "CHIJ Katong Convent",
  "CHIJ Secondary (Toa Payoh)",
  "CHIJ St. Joseph's Convent",
  "CHIJ St. Nicholas Girls' School (Secondary)",
  "CHIJ St. Theresa's Convent",
  "Christ Church Secondary School",
  "Chua Chu Kang Secondary School",
  "Chung Cheng High School (Main)",
  "Chung Cheng High School (Yishun)",
  "Clementi Town Secondary School",
  "Commonwealth Secondary School",
  "Compassvale Secondary School",
  "Crescent Girls' School",
  "Crest Secondary School",
  "Damai Secondary School",
  "Deyi Secondary School",
  "Dunearn Secondary School",
  "Dunman High School (Secondary)",
  "Dunman Secondary School",
  "East Spring Secondary School",
  "Edgefield Secondary School",
  "Evergreen Secondary School",
  "Fairfield Methodist School (Secondary)",
  "Fajar Secondary School",
  "Fuchun Secondary School",
  "Fuhua Secondary School",
  "Gan Eng Seng School",
  "Geylang Methodist School (Secondary)",
  "Greendale Secondary School",
  "Greenridge Secondary School",
  "Guangyang Secondary School",
  "Hai Sing Catholic School",
  "Hillgrove Secondary School",
  "Holy Innocents' High School",
  "Hougang Secondary School",
  "Hua Yi Secondary School",
  "Hwa Chong Institution (Secondary)",
  "Junyuan Secondary School",
  "Jurong Secondary School",
  "Jurong West Secondary School",
  "Jurongville Secondary School",
  "Juying Secondary School",
  "Kent Ridge Secondary School",
  "Kranji Secondary School",
  "Kuo Chuan Presbyterian Secondary School",
  "Loyang View Secondary School",
  "Manjusri Secondary School",
  "Maris Stella High School (Secondary)",
  "Marsiling Secondary School",
  "Mayflower Secondary School",
  "Meridian Secondary School",
  "Methodist Girls' School (Secondary)",
  "Montfort Secondary School",
  "Nan Chiau High School",
  "Nan Hua High School",
  "Nanyang Girls' High School",
  "National Junior College (Secondary)",
  "Naval Base Secondary School",
  "New Town Secondary School",
  "Ngee Ann Secondary School",
  "North Vista Secondary School",
  "Northbrooks Secondary School",
  "Northland Secondary School",
  "Northlight School",
  "NUS High School of Mathematics and Science (Secondary)",
  "Orchid Park Secondary School",
  "Outram Secondary School",
  "Pasir Ris Crest Secondary School",
  "Pasir Ris Secondary School",
  "Paya Lebar Methodist Girls' School (Secondary)",
  "Pei Hwa Secondary School",
  "Peicai Secondary School",
  "Peirce Secondary School",
  "Ping Yi Secondary School",
  "Presbyterian High School",
  "Punggol Secondary School",
  "Queenstown Secondary School",
  "Queensway Secondary School",
  "Raffles Girls' School (Secondary)",
  "Raffles Institution (Secondary)",
  "Regent Secondary School",
  "River Valley High School (Secondary)",
  "Riverside Secondary School",
  "School of Science and Technology, Singapore",
  "Sembawang Secondary School",
  "Seng Kang Secondary School",
  "Serangoon Garden Secondary School",
  "Serangoon Secondary School",
  "Singapore Chinese Girls' School",
  "Singapore Sports School (Secondary)",
  "Spectra Secondary School",
  "Springfield Secondary School",
  "St. Andrew's Secondary School",
  "St. Anthony's Canossian Secondary School",
  "St. Gabriel's Secondary School",
  "St. Hilda's Secondary School",
  "St. Joseph's Institution (Secondary)",
  "St. Margaret's Secondary School",
  "St. Patrick's School",
  "Swiss Cottage Secondary School",
  "Tampines Secondary School",
  "Tanglin Secondary School",
  "Tanjong Katong Girls' School",
  "Tanjong Katong Secondary School",
  "Teck Whye Secondary School",
  "Temasek Junior College (Secondary)",
  "Temasek Secondary School",
  "Unity Secondary School",
  "Victoria School",
  "West Spring Secondary School",
  "Westwood Secondary School",
  "Whitley Secondary School",
  "Woodgrove Secondary School",
  "Woodlands Ring Secondary School",
  "Woodlands Secondary School",
  "Xinmin Secondary School",
  "Yio Chu Kang Secondary School",
  "Yishun Secondary School",
  "Yishun Town Secondary School",
  "Yuan Ching Secondary School",
  "Yuhua Secondary School",
  "Yusof Ishak Secondary School",
  "Yuying Secondary School",
  "Zhenghua Secondary School",
  "Zhonghua Secondary School",
  "Anderson Serangoon Junior College",
  "Anglo-Chinese Junior College",
  "Anglo-Chinese School (Independent) (Junior College)",
  "Catholic Junior College",
  "Dunman High School (Junior College)",
  "Eunoia Junior College",
  "Hwa Chong Institution (Junior College)",
  "Jurong Pioneer Junior College",
  "Millennia Institute",
  "Nanyang Junior College",
  "National Junior College",
  "NUS High School of Mathematics and Science (Junior College)",
  "Raffles Institution (Junior College)",
  "River Valley High School (Junior College)",
  "School of the Arts, Singapore",
  "Singapore Sports School (Post-Secondary)",
  "St. Andrew's Junior College",
  "St. Joseph's Institution (Junior College)",
  "Tampines Meridian Junior College",
  "Temasek Junior College",
  "Victoria Junior College",
  "Yishun Innova Junior College",
  "Institute of Technical Education - College Central",
  "Institute of Technical Education - College East",
  "Institute of Technical Education - College West",
  "Nanyang Polytechnic",
  "Ngee Ann Polytechnic",
  "Republic Polytechnic",
  "Singapore Polytechnic",
  "Temasek Polytechnic",
  "National University of Singapore",
  "Nanyang Technological University",
  "Singapore Management University",
  "Singapore University of Technology and Design",
  "Singapore Institute of Technology",
  "Singapore University of Social Sciences",
  "École hôtelière de Lausanne (EHL)",
  "École Supérieure des Sciences Economiques et Commerciales (ESSEC)",
  "INSEAD",
  "S P Jain School of Global Management",
  "DigiPen Institute of Technology",
  "Curtin Singapore",
  "German Institute of Science and Technology - TUM Asia",
  "Sorbonne-Assas International Law School",
  "James Cook University Singapore",
  "St.Gallen Institute of Management in Asia",
  "Murdoch University",
  "Auston Institute of Management",
  "BAC College (Singapore)",
  "Beacon International College",
  "DIMENSIONS International College",
  "East Asia Institute of Management (EASB)",
  "ERC Institute",
  "Informatics Academy",
  "International Management & Sports College",
  "Kaplan Higher Education Academy",
  "Management Development Institute of Singapore",
  "Nanyang Institute of Management",
  "PSB Academy",
  "Raffles College of Higher Education",
  "SDH Institute	",
  "Singapore Institute of Management",
  "Singapore Raffles Music College",
  "TMC Academy",
];
